=== ArminVanBuuren/CustomApps/UZ-REPOS/SPA/PROD/SPA.SA/Dictionaries/HLR/ZTE_ROAMING/Command/Command.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Command">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Description"/>
				<xs:element name="Author">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="Date" type="xs:date" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Request" type="RequestType"/>
				<xs:element name="ErrorsList">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Error" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="Name" type="xs:string" use="required"/>
									<xs:attribute name="Value" type="ResultType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="CodePage" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ArgumentType">
		<xs:attribute name="Name" type="xs:string"/>
		<xs:attribute name="Type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="Constant"/>
					<xs:enumeration value="Parameter"/>
					<xs:enumeration value="Wellknown"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="RequestType">
		<xs:sequence>
			<xs:element name="Item" type="ArgumentType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="Template" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:simpleType name="ResultType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="SUCCESS"/>
			<xs:enumeration value="FAILURE"/>
			<xs:enumeration value="PartlyExecuted"/>
			<xs:enumeration value="WrongConfiguration"/>
			<xs:enumeration value="InvalidRequest"/>
			<xs:enumeration value="NoSubscriberIdentities"/>
			<xs:enumeration value="WrongSubscriberIdentityType"/>
			<xs:enumeration value="NoServices"/>
			<xs:enumeration value="NoBasicServices"/>
			<xs:enumeration value="NoMSISDNInBasicServices"/>
			<xs:enumeration value="NoHostForSubscriber"/>
			<xs:enumeration value="InvalidRequestParam"/>
			<xs:enumeration value="CancelOperationOnValidation"/>
			<xs:enumeration value="AbortProcessOnValidation"/>
			<xs:enumeration value="ActionNameNotFound"/>
			<xs:enumeration value="HostNotRegistred"/>
			<xs:enumeration value="NoOperationsFound"/>
			<xs:enumeration value="CommandNotFoundInRequest"/>
			<xs:enumeration value="SoftwareError"/>
			<xs:enumeration value="NoContext"/>
			<xs:enumeration value="NoRequest"/>
			<xs:enumeration value="NoDictionary"/>
			<xs:enumeration value="NoSuchServiceActivator"/>
			<xs:enumeration value="NoSuchOperation"/>
			<xs:enumeration value="NoCommandLine"/>
			<xs:enumeration value="NoPrintout"/>
			<xs:enumeration value="InvalidPrintout"/>
			<xs:enumeration value="UnregisteredError"/>
			<xs:enumeration value="NoParamListInScenario"/>
			<xs:enumeration value="NoRequestQueueInContext"/>
			<xs:enumeration value="NoResponseInContext"/>
			<xs:enumeration value="NoDetailedResultInResponse"/>
			<xs:enumeration value="UnexpectedSupplementaryServiceType"/>
			<xs:enumeration value="NoSupplementaryServices"/>
			<xs:enumeration value="TooManySupplementaryServices"/>
			<xs:enumeration value="WrongFormatOfXmlAdditionalInfo"/>
			<xs:enumeration value="NoHLREnvironment"/>
			<xs:enumeration value="NoConnectionInfo"/>
			<xs:enumeration value="NoIntNetServices"/>
			<xs:enumeration value="NoUcsiServices"/>
			<xs:enumeration value="NoGprServices"/>
			<xs:enumeration value="NoRequiredObjectInContext"/>
			<xs:enumeration value="WrongTypeOfObject"/>
			<xs:enumeration value="NoRequiredParameter"/>
			<xs:enumeration value="NoSpecifiedValueInCollection"/>
			<xs:enumeration value="NotSupportedCommandOrAction"/>
			<xs:enumeration value="NoRequiredNodeParam"/>
			<xs:enumeration value="NodeParamHasInvalidFormat"/>
			<xs:enumeration value="CannotParseASN1String"/>
			<xs:enumeration value="NoMsAttributes"/>
			<xs:enumeration value="MsisdnsAreNotEqual"/>
			<xs:enumeration value="ImsisAreNotEqual"/>
			<xs:enumeration value="AmbiguousChangeImsiData"/>
			<xs:enumeration value="ConnectionError"/>
			<xs:enumeration value="HardwareConnectionError"/>
			<xs:enumeration value="SynchronizationLost"/>
			<xs:enumeration value="SynchronizationRestored"/>
			<xs:enumeration value="BPMError"/>
			<xs:enumeration value="FailedToStoreInitialState"/>
			<xs:enumeration value="FailedToRestoreInitialState"/>
			<xs:enumeration value="BusinessProcessAborted"/>
			<xs:enumeration value="Q3Error"/>
			<xs:enumeration value="DuplicateInvocation"/>
			<xs:enumeration value="UnrecognisedOperation"/>
			<xs:enumeration value="MistypedArgument"/>
			<xs:enumeration value="ResourceLimitation"/>
			<xs:enumeration value="NoSuchObjectClass"/>
			<xs:enumeration value="NoSuchObjectInstance"/>
			<xs:enumeration value="AccessDenied"/>
			<xs:enumeration value="SyncNotSupported"/>
			<xs:enumeration value="InvalidFilter"/>
			<xs:enumeration value="NoSuchAttribute"/>
			<xs:enumeration value="InvalidAttributeValue"/>
			<xs:enumeration value="GetListError"/>
			<xs:enumeration value="SetListError"/>
			<xs:enumeration value="NoSuchAction"/>
			<xs:enumeration value="ProcessingFailure"/>
			<xs:enumeration value="DuplicateManagedObjectInstance"/>
			<xs:enumeration value="NoSuchReferenceObject"/>
			<xs:enumeration value="NoSuchEventType"/>
			<xs:enumeration value="NoSuchArgument"/>
			<xs:enumeration value="InvalidArgumentValue"/>
			<xs:enumeration value="InvalidScope"/>
			<xs:enumeration value="InvalidObjectInstance"/>
			<xs:enumeration value="MissingAttributeValue"/>
			<xs:enumeration value="ClassInstanceConflict"/>
			<xs:enumeration value="ComplexityLimitation"/>
			<xs:enumeration value="MistypedOperation"/>
			<xs:enumeration value="NoSuchInvokeId"/>
			<xs:enumeration value="OperationCancelled"/>
			<xs:enumeration value="InvalidOperation"/>
			<xs:enumeration value="InvalidOperator"/>
			<xs:enumeration value="CmisParam"/>
			<xs:enumeration value="InternalException"/>
			<xs:enumeration value="ExecutionError"/>
			<xs:enumeration value="ExecutedWithErrors"/>
			<xs:enumeration value="HardwareSpecificError"/>
			<xs:enumeration value="ImsiIsNotRegisteredInAC"/>
			<xs:enumeration value="EqualParametersInRequest"/>
			<xs:enumeration value="EqualNewMsinAndCurrentMsinInRequest"/>
			<xs:enumeration value="ImsiAssinedToAnotherSubscriber"/>
			<xs:enumeration value="MsisdnAlreadyDefined"/>
			<xs:enumeration value="NoConnectionToAuthenticationCenter"/>
			<xs:enumeration value="TimeOutWhileFetchingAuthenticationData"/>
			<xs:enumeration value="MsisdnNotDefined"/>
			<xs:enumeration value="LogicalHlrDoesNotExist"/>
			<xs:enumeration value="TwoSnAreIdentical"/>
			<xs:enumeration value="MissedMandatroryParameter"/>
			<xs:enumeration value="BasicServiceIsNotAllowed"/>
			<xs:enumeration value="EctIsGivenButChIsNotProvisioned"/>
			<xs:enumeration value="MptyIsGivenButChIsNotProvisioned"/>
			<xs:enumeration value="AnAttemptIsMadeToWithdrawChButMptyIsProvisioned"/>
			<xs:enumeration value="MsisdnAlertNumberMustExist"/>
			<xs:enumeration value="SubscriberTemplateIsNotDefined"/>
			<xs:enumeration value="InvalidParameterValue"/>
			<xs:enumeration value="NewImsiIsNotRegisteredInAC"/>
			<xs:enumeration value="OnlyCommandPromptInPrintout"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ArminVanBuuren/CustomApps/UK-REPOS/SPA/SA/MobileID/Commands/DeactivateSubscriber.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command Name="DeactivateSubscriber" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
	<Description>Отключить абонента</Description>
	<Author Name="Khovanskiy Vladimir" Date="2017-11-14+10:00"/>
	<Request>
		<RequestTemplate>
<![CDATA[
{0}
	"login" : "{2}",
	"requestId" : "{3}-{4}",
	"msisdn" : "{5}",
	"imsi" : "{6}",
	"action" : "DEACTIVATE_SUBSCRIBER"
{1}
]]>
		</RequestTemplate>
		<EmulationPrintoutTemplate><![CDATA[]]></EmulationPrintoutTemplate>
		<Item Name="SYMBOL_START" Type="Constant"/>
		<Item Name="SYMBOL_END" Type="Constant"/>
		<Item Name="LOGIN_FORIS" Type="Constant"/>
		<Item Name="org.id" Type="Wellknown"/>
		<Item Name="GlobalUid" Type="Wellknown" />
		<Item Name="msisdn" Type="Wellknown"/>
		<Item Name="imsi" Type="Wellknown"/>
	</Request>
	<ErrorsList CodePage="ASCII">
		<Error Name="SUBJ_DELETED" Value="SUCCESS"/>
		<Error Name="SIM_NOT_FOUND" Value="SUCCESS"/>
		<Error Name="DEACTIVATED" Value="SUCCESS"/>
	</ErrorsList>
</Command>

=== ArminVanBuuren/CustomApps/UZ-REPOS/SPA/PROD-ACTUAL/SPA.SA/Dictionaries/HLR/Huawei/Command/DeleteSubscriber2IMSI.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command Name="DeleteSubscriber2IMSI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
	<Description>Удаление абонента 2 IMSI</Description>
	<Author Name="Timur Khamzin" Date="2014-12-23+15:00"/>
	<Request Template='RMV SUB:IMSI="{0}";'>
		<Item Name="imsi" Type="Wellknown"/>
	</Request>
	<ErrorsList CodePage="windows-1251">
		<Error Name="ERR3007" Value="SUCCESS"/>
		<Error Name="ERR3001" Value="SUCCESS"/>
       	</ErrorsList>
</Command>
