=== ArminVanBuuren/CustomApps/UZ-REPOS/SPA/PROD/SPA.SA/Dictionaries/HLR/ZTE_ROAMING/Command/Command.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Command">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Description"/>
				<xs:element name="Author">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="Date" type="xs:date" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Request" type="RequestType"/>
				<xs:element name="ErrorsList">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Error" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="Name" type="xs:string" use="required"/>
									<xs:attribute name="Value" type="ResultType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="CodePage" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ArgumentType">
		<xs:attribute name="Name" type="xs:string"/>
		<xs:attribute name="Type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="Constant"/>
					<xs:enumeration value="Parameter"/>
					<xs:enumeration value="Wellknown"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="RequestType">
		<xs:sequence>
			<xs:element name="Item" type="ArgumentType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="Template" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:simpleType name="ResultType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="SUCCESS"/>
			<xs:enumeration value="FAILURE"/>
			<xs:enumeration value="PartlyExecuted"/>
			<xs:enumeration value="WrongConfiguration"/>
			<xs:enumeration value="InvalidRequest"/>
			<xs:enumeration value="NoSubscriberIdentities"/>
			<xs:enumeration value="WrongSubscriberIdentityType"/>
			<xs:enumeration value="NoServices"/>
			<xs:enumeration value="NoBasicServices"/>
			<xs:enumeration value="NoMSISDNInBasicServices"/>
			<xs:enumeration value="NoHostForSubscriber"/>
			<xs:enumeration value="InvalidRequestParam"/>
			<xs:enumeration value="CancelOperationOnValidation"/>
			<xs:enumeration value="AbortProcessOnValidation"/>
			<xs:enumeration value="ActionNameNotFound"/>
			<xs:enumeration value="HostNotRegistred"/>
			<xs:enumeration value="NoOperationsFound"/>
			<xs:enumeration value="CommandNotFoundInRequest"/>
			<xs:enumeration value="SoftwareError"/>
			<xs:enumeration value="NoContext"/>
			<xs:enumeration value="NoRequest"/>
			<xs:enumeration value="NoDictionary"/>
			<xs:enumeration value="NoSuchServiceActivator"/>
			<xs:enumeration value="NoSuchOperation"/>
			<xs:enumeration value="NoCommandLine"/>
			<xs:enumeration value="NoPrintout"/>
			<xs:enumeration value="InvalidPrintout"/>
			<xs:enumeration value="UnregisteredError"/>
			<xs:enumeration value="NoParamListInScenario"/>
			<xs:enumeration value="NoRequestQueueInContext"/>
			<xs:enumeration value="NoResponseInContext"/>
			<xs:enumeration value="NoDetailedResultInResponse"/>
			<xs:enumeration value="UnexpectedSupplementaryServiceType"/>
			<xs:enumeration value="NoSupplementaryServices"/>
			<xs:enumeration value="TooManySupplementaryServices"/>
			<xs:enumeration value="WrongFormatOfXmlAdditionalInfo"/>
			<xs:enumeration value="NoHLREnvironment"/>
			<xs:enumeration value="NoConnectionInfo"/>
			<xs:enumeration value="NoIntNetServices"/>
			<xs:enumeration value="NoUcsiServices"/>
			<xs:enumeration value="NoGprServices"/>
			<xs:enumeration value="NoRequiredObjectInContext"/>
			<xs:enumeration value="WrongTypeOfObject"/>
			<xs:enumeration value="NoRequiredParameter"/>
			<xs:enumeration value="NoSpecifiedValueInCollection"/>
			<xs:enumeration value="NotSupportedCommandOrAction"/>
			<xs:enumeration value="NoRequiredNodeParam"/>
			<xs:enumeration value="NodeParamHasInvalidFormat"/>
			<xs:enumeration value="CannotParseASN1String"/>
			<xs:enumeration value="NoMsAttributes"/>
			<xs:enumeration value="MsisdnsAreNotEqual"/>
			<xs:enumeration value="ImsisAreNotEqual"/>
			<xs:enumeration value="AmbiguousChangeImsiData"/>
			<xs:enumeration value="ConnectionError"/>
			<xs:enumeration value="HardwareConnectionError"/>
			<xs:enumeration value="SynchronizationLost"/>
			<xs:enumeration value="SynchronizationRestored"/>
			<xs:enumeration value="BPMError"/>
			<xs:enumeration value="FailedToStoreInitialState"/>
			<xs:enumeration value="FailedToRestoreInitialState"/>
			<xs:enumeration value="BusinessProcessAborted"/>
			<xs:enumeration value="Q3Error"/>
			<xs:enumeration value="DuplicateInvocation"/>
			<xs:enumeration value="UnrecognisedOperation"/>
			<xs:enumeration value="MistypedArgument"/>
			<xs:enumeration value="ResourceLimitation"/>
			<xs:enumeration value="NoSuchObjectClass"/>
			<xs:enumeration value="NoSuchObjectInstance"/>
			<xs:enumeration value="AccessDenied"/>
			<xs:enumeration value="SyncNotSupported"/>
			<xs:enumeration value="InvalidFilter"/>
			<xs:enumeration value="NoSuchAttribute"/>
			<xs:enumeration value="InvalidAttributeValue"/>
			<xs:enumeration value="GetListError"/>
			<xs:enumeration value="SetListError"/>
			<xs:enumeration value="NoSuchAction"/>
			<xs:enumeration value="ProcessingFailure"/>
			<xs:enumeration value="DuplicateManagedObjectInstance"/>
			<xs:enumeration value="NoSuchReferenceObject"/>
			<xs:enumeration value="NoSuchEventType"/>
			<xs:enumeration value="NoSuchArgument"/>
			<xs:enumeration value="InvalidArgumentValue"/>
			<xs:enumeration value="InvalidScope"/>
			<xs:enumeration value="InvalidObjectInstance"/>
			<xs:enumeration value="MissingAttributeValue"/>
			<xs:enumeration value="ClassInstanceConflict"/>
			<xs:enumeration value="ComplexityLimitation"/>
			<xs:enumeration value="MistypedOperation"/>
			<xs:enumeration value="NoSuchInvokeId"/>
			<xs:enumeration value="OperationCancelled"/>
			<xs:enumeration value="InvalidOperation"/>
			<xs:enumeration value="InvalidOperator"/>
			<xs:enumeration value="CmisParam"/>
			<xs:enumeration value="InternalException"/>
			<xs:enumeration value="ExecutionError"/>
			<xs:enumeration value="ExecutedWithErrors"/>
			<xs:enumeration value="HardwareSpecificError"/>
			<xs:enumeration value="ImsiIsNotRegisteredInAC"/>
			<xs:enumeration value="EqualParametersInRequest"/>
			<xs:enumeration value="EqualNewMsinAndCurrentMsinInRequest"/>
			<xs:enumeration value="ImsiAssinedToAnotherSubscriber"/>
			<xs:enumeration value="MsisdnAlreadyDefined"/>
			<xs:enumeration value="NoConnectionToAuthenticationCenter"/>
			<xs:enumeration value="TimeOutWhileFetchingAuthenticationData"/>
			<xs:enumeration value="MsisdnNotDefined"/>
			<xs:enumeration value="LogicalHlrDoesNotExist"/>
			<xs:enumeration value="TwoSnAreIdentical"/>
			<xs:enumeration value="MissedMandatroryParameter"/>
			<xs:enumeration value="BasicServiceIsNotAllowed"/>
			<xs:enumeration value="EctIsGivenButChIsNotProvisioned"/>
			<xs:enumeration value="MptyIsGivenButChIsNotProvisioned"/>
			<xs:enumeration value="AnAttemptIsMadeToWithdrawChButMptyIsProvisioned"/>
			<xs:enumeration value="MsisdnAlertNumberMustExist"/>
			<xs:enumeration value="SubscriberTemplateIsNotDefined"/>
			<xs:enumeration value="InvalidParameterValue"/>
			<xs:enumeration value="NewImsiIsNotRegisteredInAC"/>
			<xs:enumeration value="OnlyCommandPromptInPrintout"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ArminVanBuuren/CustomApps/UZ-REPOS/SPA/EDITION/SPA.SA/SPA.SA.HLR.ZTE/Commands/GetLOCDataByMsisdn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by name (company) -->
<Command Name="GetLOCDataByMsisdn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
	<Description>Запрос локации абонента</Description>
	<Author Name="Timur Khamzin" Date="2015-11-16+15:00"/>
	<Request Template='Qry User:MSISDN={0},Item=LOC;^M'>
		<Item Name="msisdn" Type="Wellknown"/>
	</Request>
	<ErrorsList CodePage="windows-1251">
		<Error Name="ERR3001" Value="NoSuchObjectInstance"/>
		<Error Name="" Value="SUCCESS"/>
	</ErrorsList>
</Command>

=== ArminVanBuuren/CustomApps/Minsk-REPOS/SPA/PROD-2020.02.06/SPA.SA/Contents/UnsubContentUnknown/dictionaries/Commands/Unsubscribe.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command Name="Unsubscribe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
	<Description>Удаление профиля</Description>
	<Author Name="YAI" Date="2015-04-08+10:36"/>
	<Request Template="?msisdn={0}">
		<Item Name="msisdn" Type="Wellknown"/>
	</Request>
	<ErrorsList CodePage="ASCII">
		<Error Name=" 200 OK" Value="SUCCESS"/>
		<Error Name="500" Value="FAILURE"/>
	</ErrorsList>
</Command>

=== ArminVanBuuren/CustomApps/Minsk-REPOS/SPA/PROD-2019.09.01/SPA.SA/TechPlatforms/LBS/dictionaries/Commands/BlockFamilyHereLBS.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command Name="BlockFamilyHereLBS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
	<Description>BlockFamilyHereLBS</Description>
	<Author Name="NNM" Date="2020-01-10+10:55"/>
	<Request Template="msisdn={0}&#38;servicecode=FR17276">
	<Item Name="msisdn" Type="Wellknown" />
	</Request>
	<ErrorsList CodePage="ASCII">
		<Error Name="&#34;result&#34;:0" Value="SUCCESS"/>
		<Error Name="&#34;result&#34;:1" Value="SUCCESS"/>
		<Error Name="&#34;result&#34;:-1" Value="MsisdnNotDefined"/>
	</ErrorsList>
</Command>

=== ArminVanBuuren/CustomApps/Minsk-REPOS/SPA/FORIS6/SPA.SA/Contents/RBT/Commands/old/CreateRBT.xml
<Command Name="CreateRBT" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
  <Description>Создание профиля абонента</Description>
  <Author Name="Valery Bushkarev" Date="2005-05-16+11:09" />
  <Request Template="CommandCode=CREATE&amp;MSISDN={0}&amp;MacroRegion=MRGCE&amp;NewMSISDN=&amp;MDateTime={1:ddMMyyyyHHmmss}">
    <Item Name="msisdn.fn" Type="Wellknown" />
    <Item Name="datetime" Type="Wellknown" />
  </Request>
  <ErrorsList CodePage="ASCII">
    <Error Name="101;" Expression="$(Error)" Value="SUCCESS" />
  </ErrorsList>
</Command>

=== ArminVanBuuren/CustomApps/Minsk-REPOS/SPA/PROD-2019.09.01/SPA.SA/Archive/VMS/dictionaries/Commands/DeleteSubscriberonVD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command Name="DeleteSubscriberonVD" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
	<Description>DeleteSubscriber</Description>
	<Author Name="YAI" Date="2013-04-15+10:50"/>
	<Request Template="userdelete.php?blogin=MTSby_bill_login&amp;bpsw=EcRd3wHOvGhZa_k&amp;ulogin={0}&amp;xml=1">
	<Item Name="msisdn" Type="Wellknown" />
	</Request>
	<ErrorsList CodePage="ASCII">
		<Error Name="&lt;RESULT&gt;1&lt;/RESULT&gt;" Value="SUCCESS"/>
		<Error Name="&lt;RESULT&gt;0&lt;/RESULT&gt;" Value="SUCCESS"/>
	</ErrorsList>
</Command>

=== ArminVanBuuren/CustomApps/UZ-REPOS/SPA/EDITION/SPA.SA/SPA.SA.EIR/Commands/GetHistoryOnEIR.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command Name="GetHistoryOnEIR" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
	<Description>Получение истории</Description>
	<Author Name="Timur Khamzin" Date="2019-04-04+05:00"/>
	<Request Template="cmd=gethistory&amp;imsi={1}&amp;msisdn={0}&amp;pastdays={2}">
		<Item Name="msisdn" Type="Wellknown"/>
		<Item Name="imsi" Type="Wellknown"/>
                <Item Name="pastdays" Type="Parameter"/>
	</Request>                                                                                            
	<ErrorsList CodePage="ASCII"/>
</Command>

=== ArminVanBuuren/CustomApps/Minsk-REPOS/SPA/PROD-2019.09.01/SPA.SA/IMMO_Services/dictionaries/Commands/ChangeMSISDNInteractiveBalance.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command Name="ChangeMSISDNInteractiveBalance" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
	<Description>Замена номера</Description>
	<Author Name="YAI" Date="2018-10-15+13:25"/>
	<Request Template="">
		<Item Name="msisdn" Type="Wellknown"/> 
		<Item Name="newmsisdn2" Type="Wellknown"/> 
	</Request>
	<ErrorsList CodePage="ascii" >
		<Error Name="200 ok" Value="SUCCESS" />
		<Error Name="200 OK" Value="SUCCESS" />
		<Error Name="404 " Value="SUCCESS" />
		<Error Name="User not found" Value="SUCCESS" />
		<Error Name="500 " Value="ResourceLimitation" />
	</ErrorsList>
</Command>

=== ArminVanBuuren/CustomApps/Minsk-REPOS/SPA/PROD-2019.09.01/SPA.SA/TechPlatforms/LBS/dictionaries/Commands/DeleteServiceAdminLBS.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command Name="DeleteServiceAdminLBS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Command.xsd">
	<Description>DeleteServiceAdminLBS</Description>
	<Author Name="NNM" Date="2019-09-25+10:55"/>
	<Request Template="msisdn={0}&#38;servicecode=FR17148">
	<Item Name="msisdn" Type="Wellknown" />
	</Request>
	<ErrorsList CodePage="ASCII">
		<Error Name="&#34;result&#34;:0" Value="SUCCESS"/>
		<Error Name="&#34;result&#34;:1" Value="SUCCESS"/>
		<Error Name="&#34;result&#34;:-1" Value="SUCCESS"/>
	</ErrorsList>
</Command>
